/*
 * This source file was generated by the Gradle 'init' task
 */
package tech.sco.hetznerkloud

import io.kotest.common.runBlocking
import io.kotest.core.spec.style.AnnotationSpec
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.assertThrows
import tech.sco.hetznerkloud.model.UnauthorizedError

private const val TEST_TOKEN = "foo"

class CloudApiClientTest : AnnotationSpec() {
    private val apiToken = ApiToken(TEST_TOKEN)
    private val mockEngine = createMockEngine(apiToken)

    @Test
    fun shouldThrowUnauthorizedError() {
        val underTest = CloudApiClient.of(ApiToken("invalid token"), mockEngine)

        runBlocking {
            assertThrows<UnauthorizedError> {
                underTest.servers.all()
            }
        }
    }
}
