/*
 * This source file was generated by the Gradle 'init' task
 */
package tech.sco.hetznerkloud

import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.engine.HttpClientEngine
import io.ktor.client.engine.cio.CIO
import io.ktor.client.plugins.auth.Auth
import io.ktor.client.plugins.auth.providers.BearerTokens
import io.ktor.client.plugins.auth.providers.bearer
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.request.request
import io.ktor.client.request.setBody
import io.ktor.http.ContentType
import io.ktor.http.appendPathSegments
import io.ktor.http.contentType
import io.ktor.serialization.kotlinx.json.json
import kotlinx.serialization.json.Json
import tech.sco.hetznerkloud.model.Datacenter
import tech.sco.hetznerkloud.request.CreateServer
import tech.sco.hetznerkloud.request.HttpMessage
import tech.sco.hetznerkloud.response.ActionList
import tech.sco.hetznerkloud.response.DatacenterList
import tech.sco.hetznerkloud.response.ImageList
import tech.sco.hetznerkloud.response.IsoList
import tech.sco.hetznerkloud.response.ServerCreated
import tech.sco.hetznerkloud.response.ServerItem
import tech.sco.hetznerkloud.response.ServerList

private const val BASE_URL = "https://api.hetzner.cloud/v1"

class CloudApiClient private constructor(
    httpEngine: HttpClientEngine,
    private val token: ApiToken,
) {
    private val client =
        HttpClient(httpEngine) {
            install(ContentNegotiation) {
                json(
                    Json {
//                        ignoreUnknownKeys = true
//                        isLenient = true
                    },
                )
            }
            install(Auth) {
                bearer {
                    loadTokens {
                        BearerTokens(accessToken = token.value, refreshToken = null)
                    }
                }
            }
        }

    companion object {
        fun of(
            token: ApiToken,
            httpEngine: HttpClientEngine = CIO.create(),
        ) = CloudApiClient(httpEngine, token)
    }

    suspend fun actions(): ActionList = request(Route.GET_ALL_ACTIONS)

    suspend fun action(id: Long): ActionList = request(Route.GET_ACTION, id)

    suspend fun servers(): ServerList = request(Route.GET_ALL_SERVERS)

    suspend fun server(id: Long): ServerItem = request(Route.GET_SERVER, id)

    suspend fun server(request: CreateServer): ServerCreated = request(Route.CREATE_SERVER, body = request)

    suspend fun datacenters(): DatacenterList = request(Route.GET_ALL_DATACENTERS)

    suspend fun datacenter(id: Long): DatacenterList = request(Route.GET_DATACENTER, id)

    suspend fun images(): ImageList = request(Route.GET_ALL_IMAGES)

    suspend fun image(id: Long): ImageList = request(Route.GET_IMAGE, id)

    suspend fun isos(): IsoList = request(Route.GET_ALL_ISOS)

    suspend fun iso(id: Long): IsoList = request(Route.GET_ISO, id)

    suspend fun serverTypes(): Datacenter.ServerTypes = request(Route.GET_ALL_SERVER_TYPES)

    suspend fun serverType(id: Long): Datacenter.ServerTypes = request(Route.GET_SERVER_TYPE, id)

    private suspend inline fun <reified T> request(route: Route, resourceId: Long? = null, body: HttpMessage? = null): T =
        route.value.let {
            val (httpMethod, path) = it

            client
                .request(BASE_URL) {
                    method = httpMethod
                    url {
                        if (resourceId != null) {
                            appendPathSegments(path.withId(resourceId).value)
                        } else {
                            appendPathSegments(path.value)
                        }
                    }
                    if (body != null) {
                        contentType(ContentType.Application.Json)
                        setBody(body)
                    }
                }.body()
        }
}
